name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout node action
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: 'yarn.lock'

      - name: Install NPM dependencies
        run: yarn install --verbose

      - name: Check ESLint
        run: yarn lint

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout node action
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: '**/yarn.lock'

      - name: Install NPM dependencies
        run: yarn install --verbose

      - name: Runs compile asset script
        working-directory: ./packages/wallet-sdk
        run: node ./compile-assets.js

      - name: Check Types
        run: yarn typecheck

  tests:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/wallet-sdk

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: '**/yarn.lock'

      - name: Install NPM dependencies
        run: yarn install --verbose

      - name: Runs compile asset script
        run: node ./compile-assets.js

      - name: Run Unit Tests
        run: yarn test:unit
