name: Tag

on:
  push:
    # branches:
    #   - master

jobs:
  tag_merged_version:
    if: startsWith(github.event.head_commit.message, 'v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Tag Match
        id: check-tag
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo ::set-output name=match::true
          fi

      - name: Set Tag Value
        if: steps.check-tag.outputs.match == 'true'
        id: tag
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          TAG=$(echo $COMMIT_MSG | sed 's/^v[0-9]+\.[0-9]+\.[0-9]+/$1/g')
          echo "PARSED_TAG=$TAG" >> $GITHUB_ENV

      - name: Tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.PARSED_TAG }}",
              sha: context.sha
            })